### ISSUE TITLE
Dirty Reload

### ISSUE THREAD

**Issue by userbradley** [devhmars/mkdocs_site#2]
Worth adding the below in for your `Tasfile`

```yaml
  serve:
    cmds:
      - mkdocs serve --dirtyreload
```

It does a much faster reload of the site especially when you start getting in to 50+ pages

[GH Issue on Dirty Reload](https://github.com/mkdocs/mkdocs/issues/990)

One thing to note, is you should always do `mkdocs serve` first to build the search as well as the nav as these arent enabled on the dirty reload
